#ifndef CHAR_TO_SCANCODE
#define CHAR_TO_SCANCODE

void char_to_scancode(char character, SDL_Scancode *scancode0, SDL_Scancode *scancode1){
        if(character == '\n') *scancode0 = SDL_SCANCODE_RETURN;
        else if(character == ' ') *scancode0 = SDL_SCANCODE_SPACE;
        else if(character == '!') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_1;
        else if(character == '"') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_APOSTROPHE;
        else if(character == '$') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_4;
        else if(character == '%') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_5;
        else if(character == '&') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_7;
        else if(character == '\'') *scancode0 = SDL_SCANCODE_APOSTROPHE;
        else if(character == '(') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_9;
        else if(character == ')') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_0;
        else if(character == '*') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_8;
        else if(character == '+') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_EQUALS;
        else if(character == ',') *scancode0 = SDL_SCANCODE_COMMA;
        else if(character == '-') *scancode0 = SDL_SCANCODE_MINUS;
        else if(character == '.') *scancode0 = SDL_SCANCODE_PERIOD;
        else if(character == '/') *scancode0 = SDL_SCANCODE_SLASH;
        else if(character == '0') *scancode0 = SDL_SCANCODE_0;
        else if(character == '1') *scancode0 = SDL_SCANCODE_1;
        else if(character == '2') *scancode0 = SDL_SCANCODE_2;
        else if(character == '3') *scancode0 = SDL_SCANCODE_3;
        else if(character == '4') *scancode0 = SDL_SCANCODE_4;
        else if(character == '5') *scancode0 = SDL_SCANCODE_5;
        else if(character == '6') *scancode0 = SDL_SCANCODE_6;
        else if(character == '7') *scancode0 = SDL_SCANCODE_7;
        else if(character == '8') *scancode0 = SDL_SCANCODE_8;
        else if(character == '9') *scancode0 = SDL_SCANCODE_9;
        else if(character == ':') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_SEMICOLON;
        else if(character == ';') *scancode0 = SDL_SCANCODE_SEMICOLON;
        else if(character == '<') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_COMMA;
        else if(character == '=') *scancode0 = SDL_SCANCODE_EQUALS;
        else if(character == '>') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_PERIOD;
        else if(character == '?') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_SLASH;
        else if(character == '@') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_2;
        else if(character == 'A') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_A;
        else if(character == 'B') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_B;
        else if(character == 'C') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_C;
        else if(character == 'D') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_D;
        else if(character == 'E') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_E;
        else if(character == 'F') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_F;
        else if(character == 'G') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_G;
        else if(character == 'H') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_H;
        else if(character == 'I') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_I;
        else if(character == 'J') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_J;
        else if(character == 'K') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_K;
        else if(character == 'L') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_L;
        else if(character == 'M') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_M;
        else if(character == 'N') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_N;
        else if(character == 'O') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_O;
        else if(character == 'P') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_P;
        else if(character == 'Q') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_Q;
        else if(character == 'R') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_R;
        else if(character == 'S') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_S;
        else if(character == 'T') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_T;
        else if(character == 'U') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_U;
        else if(character == 'V') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_V;
        else if(character == 'W') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_W;
        else if(character == 'X') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_X;
        else if(character == 'Y') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_Y;
        else if(character == 'Z') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_Z;
        else if(character == '[') *scancode0 = SDL_SCANCODE_LEFTBRACKET;
        else if(character == '\\') *scancode0 = SDL_SCANCODE_BACKSLASH;
        else if(character == ']') *scancode0 = SDL_SCANCODE_RIGHTBRACKET;
        else if(character == '^') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_6;
        else if(character == '_') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_MINUS;
        else if(character == '`') *scancode0 = SDL_SCANCODE_GRAVE;
        else if(character == 'a') *scancode0 = SDL_SCANCODE_A;
        else if(character == 'b') *scancode0 = SDL_SCANCODE_B;
        else if(character == 'c') *scancode0 = SDL_SCANCODE_C;
        else if(character == 'd') *scancode0 = SDL_SCANCODE_D;
        else if(character == 'e') *scancode0 = SDL_SCANCODE_E;
        else if(character == 'f') *scancode0 = SDL_SCANCODE_F;
        else if(character == 'g') *scancode0 = SDL_SCANCODE_G;
        else if(character == 'h') *scancode0 = SDL_SCANCODE_H;
        else if(character == 'i') *scancode0 = SDL_SCANCODE_I;
        else if(character == 'j') *scancode0 = SDL_SCANCODE_J;
        else if(character == 'k') *scancode0 = SDL_SCANCODE_K;
        else if(character == 'l') *scancode0 = SDL_SCANCODE_L;
        else if(character == 'm') *scancode0 = SDL_SCANCODE_M;
        else if(character == 'n') *scancode0 = SDL_SCANCODE_N;
        else if(character == 'o') *scancode0 = SDL_SCANCODE_O;
        else if(character == 'p') *scancode0 = SDL_SCANCODE_P;
        else if(character == 'q') *scancode0 = SDL_SCANCODE_Q;
        else if(character == 'r') *scancode0 = SDL_SCANCODE_R;
        else if(character == 's') *scancode0 = SDL_SCANCODE_S;
        else if(character == 't') *scancode0 = SDL_SCANCODE_T;
        else if(character == 'u') *scancode0 = SDL_SCANCODE_U;
        else if(character == 'v') *scancode0 = SDL_SCANCODE_V;
        else if(character == 'w') *scancode0 = SDL_SCANCODE_W;
        else if(character == 'x') *scancode0 = SDL_SCANCODE_X;
        else if(character == 'y') *scancode0 = SDL_SCANCODE_Y;
        else if(character == 'z') *scancode0 = SDL_SCANCODE_Z;
        else if(character == '{') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_LEFTBRACKET;
        else if(character == '|') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_BACKSLASH;
        else if(character == '}') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_RIGHTBRACKET;
        else if(character == '~') *scancode0 = SDL_SCANCODE_LSHIFT, *scancode1 = SDL_SCANCODE_GRAVE;
}

#endif
