
#include <unordered_map>
#include <SDL2/SDL.h>

struct PS2_scancode {
    const char* key_make;
    const char* key_break;
};

const std::unordered_map<SDL_Scancode, PS2_scancode> ps2_map = {

    { SDL_SCANCODE_A, {"\x1c", "\xf0\x1c"} },
    { SDL_SCANCODE_B, {"\x32", "\xf0\x32"} },
    { SDL_SCANCODE_C, {"\x21", "\xf0\x21"} },
    { SDL_SCANCODE_D, {"\x23", "\xf0\x23"} },
    { SDL_SCANCODE_E, {"\x24", "\xf0\x24"} },
    { SDL_SCANCODE_F, {"\x2b", "\xf0\x2b"} },
    { SDL_SCANCODE_G, {"\x34", "\xf0\x34"} },
    { SDL_SCANCODE_H, {"\x33", "\xf0\x33"} },
    { SDL_SCANCODE_I, {"\x43", "\xf0\x43"} },
    { SDL_SCANCODE_J, {"\x3b", "\xf0\x3b"} },
    { SDL_SCANCODE_K, {"\x42", "\xf0\x42"} },
    { SDL_SCANCODE_L, {"\x4b", "\xf0\x4b"} },
    { SDL_SCANCODE_M, {"\x3a", "\xf0\x3a"} },
    { SDL_SCANCODE_N, {"\x31", "\xf0\x31"} },
    { SDL_SCANCODE_O, {"\x44", "\xf0\x44"} },
    { SDL_SCANCODE_P, {"\x4d", "\xf0\x4d"} },
    { SDL_SCANCODE_Q, {"\x15", "\xf0\x15"} },
    { SDL_SCANCODE_R, {"\x2d", "\xf0\x2d"} },
    { SDL_SCANCODE_S, {"\x1b", "\xf0\x1b"} },
    { SDL_SCANCODE_T, {"\x2c", "\xf0\x2c"} },
    { SDL_SCANCODE_U, {"\x3c", "\xf0\x3c"} },
    { SDL_SCANCODE_V, {"\x2a", "\xf0\x2a"} },
    { SDL_SCANCODE_W, {"\x1d", "\xf0\x1d"} },
    { SDL_SCANCODE_X, {"\x22", "\xf0\x22"} },
    { SDL_SCANCODE_Y, {"\x35", "\xf0\x35"} },
    { SDL_SCANCODE_Z, {"\x1a", "\xf0\x1a"} },
    { SDL_SCANCODE_0, {"\x45", "\xf0\x45"} },
    { SDL_SCANCODE_1, {"\x16", "\xf0\x16"} },
    { SDL_SCANCODE_2, {"\x1e", "\xf0\x1e"} },
    { SDL_SCANCODE_3, {"\x26", "\xf0\x26"} },
    { SDL_SCANCODE_4, {"\x25", "\xf0\x25"} },
    { SDL_SCANCODE_5, {"\x2e", "\xf0\x2e"} },
    { SDL_SCANCODE_6, {"\x36", "\xf0\x36"} },
    { SDL_SCANCODE_7, {"\x3d", "\xf0\x3d"} },
    { SDL_SCANCODE_8, {"\x3e", "\xf0\x3e"} },
    { SDL_SCANCODE_9, {"\x46", "\xf0\x46"} },
    { SDL_SCANCODE_GRAVE, {"\x0e", "\xf0\x0e"} },
    { SDL_SCANCODE_MINUS, {"\x4e", "\xf0\x4e"} },
    { SDL_SCANCODE_EQUALS, {"\x55", "\xf0\x55"} },
    { SDL_SCANCODE_BACKSLASH, {"\x5d", "\xf0\x5d"} },
    { SDL_SCANCODE_BACKSPACE, {"\x66", "\xf0\x66"} },
    { SDL_SCANCODE_SPACE, {"\x29", "\xf0\x29"} },
    { SDL_SCANCODE_TAB, {"\x0d", "\xf0\x0d"} },
    { SDL_SCANCODE_CAPSLOCK, {"\x58", "\xf0\x58"} },
    { SDL_SCANCODE_LSHIFT, {"\x12", "\xf0\x12"} },
    { SDL_SCANCODE_LCTRL, {"\x14", "\xf0\x14"} },
    { SDL_SCANCODE_LGUI, {"\xe0\x1f", "\xe0\xf0\x1f"} },
    { SDL_SCANCODE_LALT, {"\x11", "\xf0\x11"} },
    { SDL_SCANCODE_RSHIFT, {"\x59", "\xf0\x59"} },
    { SDL_SCANCODE_RCTRL, {"\xe0\x14", "\xe0\xf0\x14"} },
    { SDL_SCANCODE_RGUI, {"\xe0\x27", "\xe0\xf0\x27"} },
    { SDL_SCANCODE_RALT, {"\xe0\x11", "\xe0\xf0\x11"} },
    { SDL_SCANCODE_APPLICATION, {"\xe0\x2f", "\xe0\xf0\x2f"} },
    { SDL_SCANCODE_RETURN, {"\x5a", "\xf0\x5a"} },
    { SDL_SCANCODE_ESCAPE, {"\x76", "\xf0\x76"} },
    { SDL_SCANCODE_F1, {"\x05", "\xf0\x05"} },
    { SDL_SCANCODE_F2, {"\x06", "\xf0\x06"} },
    { SDL_SCANCODE_F3, {"\x04", "\xf0\x04"} },
    { SDL_SCANCODE_F4, {"\x0c", "\xf0\x0c"} },
    { SDL_SCANCODE_F5, {"\x03", "\xf0\x03"} },
    { SDL_SCANCODE_F6, {"\x0b", "\xf0\x0b"} },
    { SDL_SCANCODE_F7, {"\x83", "\xf0\x83"} },
    { SDL_SCANCODE_F8, {"\x0a", "\xf0\x0a"} },
    { SDL_SCANCODE_F9, {"\x01", "\xf0\x01"} },
    { SDL_SCANCODE_F10, {"\x09", "\xf0\x09"} },
    { SDL_SCANCODE_F11, {"\x78", "\xf0\x78"} },
    { SDL_SCANCODE_F12, {"\x07", "\xf0\x07"} },
    { SDL_SCANCODE_PRINTSCREEN, {"\xe0\x12\xe0\x7c", "\xe0\xf0\x7c\xe0\xf0\x12"} },
    { SDL_SCANCODE_SCROLLLOCK, {"\x7e", "\xf0\x7e"} },
    { SDL_SCANCODE_PAUSE, {"\xe1\x14\x77\xe1\xf0\x14\xf0\x77", "\x00"} },
    { SDL_SCANCODE_LEFTBRACKET, {"\x54", "\xf0\x54"} },
    { SDL_SCANCODE_INSERT, {"\xe0\x70", "\xe0\xf0\x70"} },
    { SDL_SCANCODE_HOME, {"\xe0\x6c", "\xe0\xf0\x6c"} },
    { SDL_SCANCODE_PAGEUP, {"\xe0\x7d", "\xe0\xf0\x7d"} },
    { SDL_SCANCODE_DELETE, {"\xe0\x71", "\xe0\xf0\x71"} },
    { SDL_SCANCODE_END, {"\xe0\x69", "\xe0\xf0\x69"} },
    { SDL_SCANCODE_PAGEDOWN, {"\xe0\x7a", "\xe0\xf0\x7a"} },
    { SDL_SCANCODE_UP, {"\xe0\x75", "\xe0\xf0\x75"} },
    { SDL_SCANCODE_LEFT, {"\xe0\x6b", "\xe0\xf0\x6b"} },
    { SDL_SCANCODE_DOWN, {"\xe0\x72", "\xe0\xf0\x72"} },
    { SDL_SCANCODE_RIGHT, {"\xe0\x74", "\xe0\xf0\x74"} },
    { SDL_SCANCODE_NUMLOCKCLEAR, {"\x77", "\xf0\x77"} },
    { SDL_SCANCODE_KP_DIVIDE, {"\xe0\x4a", "\xe0\xf0\x4a"} },
    { SDL_SCANCODE_KP_MULTIPLY, {"\x7c", "\xf0\x7c"} },
    { SDL_SCANCODE_KP_MINUS, {"\x7b", "\xf0\x7b"} },
    { SDL_SCANCODE_KP_PLUS, {"\x79", "\xf0\x79"} },
    { SDL_SCANCODE_KP_ENTER, {"\xe0\x5a", "\xe0\xf0\x5a"} },
    { SDL_SCANCODE_KP_PERIOD, {"\x71", "\xf0\x71"} },
    { SDL_SCANCODE_KP_0, {"\x70", "\xf0\x70"} },
    { SDL_SCANCODE_KP_1, {"\x69", "\xf0\x69"} },
    { SDL_SCANCODE_KP_2, {"\x72", "\xf0\x72"} },
    { SDL_SCANCODE_KP_3, {"\x7a", "\xf0\x7a"} },
    { SDL_SCANCODE_KP_4, {"\x6b", "\xf0\x6b"} },
    { SDL_SCANCODE_KP_5, {"\x73", "\xf0\x73"} },
    { SDL_SCANCODE_KP_6, {"\x74", "\xf0\x74"} },
    { SDL_SCANCODE_KP_7, {"\x6c", "\xf0\x6c"} },
    { SDL_SCANCODE_KP_8, {"\x75", "\xf0\x75"} },
    { SDL_SCANCODE_KP_9, {"\x7d", "\xf0\x7d"} },
    { SDL_SCANCODE_RIGHTBRACKET, {"\x5b", "\xf0\x5b"} },
    { SDL_SCANCODE_SEMICOLON, {"\x4c", "\xf0\x4c"} },
    { SDL_SCANCODE_APOSTROPHE, {"\x52", "\xf0\x52"} },
    { SDL_SCANCODE_COMMA, {"\x41", "\xf0\x41"} },
    { SDL_SCANCODE_PERIOD, {"\x49", "\xf0\x49"} },
    { SDL_SCANCODE_SLASH, {"\x4a", "\xf0\x4a"} },

};

